#include "duckdb/logging/file_system_logger.hpp"

namespace duckdb {

#define DUCKDB_LOG_OPEN_CACHE_HIT(HANDLE)  DUCKDB_LOG_FILE_SYSTEM(HANDLE, "FILE OPEN CACHE HIT");
#define DUCKDB_LOG_OPEN_CACHE_MISS(HANDLE) DUCKDB_LOG_FILE_SYSTEM(HANDLE, "FILE OPEN CACHE MISS");

#define DUCKDB_LOG_READ_CACHE_HIT(HANDLE)  DUCKDB_LOG_FILE_SYSTEM(HANDLE, "FILE READ CACHE HIT");
#define DUCKDB_LOG_READ_CACHE_MISS(HANDLE) DUCKDB_LOG_FILE_SYSTEM(HANDLE, "FILE READ CACHE MISS");

} // namespace duckdb
